In [13]:
from sklearn.metrics import confusion_matrix, classification_report

from batch_generator import BatchGenerator
from neural_network import NeuralNetwork

In [14]:
batch_generator = BatchGenerator(1)
nn = NeuralNetwork([784,60,10])

In [15]:
nn.train(batch_generator)

In [16]:
x_test, y_test = batch_generator.test_data

predictions = []
true_labels = []
for i in range(x_test.shape[0]):
    predictions.append(nn.inference(np.atleast_2d(x_test[i])))
    true_labels.append(np.argmax(y_test[i]))
    
print(confusion_matrix(true_labels,predictions))
print(classification_report(true_labels,predictions))

[[ 967    0    0    1    0    2    4    2    4    0]
 [   1 1119    4    1    0    1    6    0    3    0]
 [   6    2  984   11    6    0    5    6   11    1]
 [   0    0   10  981    0    5    0    6    5    3]
 [   1    2    1    0  943    1   14    1    4   15]
 [   8    0    0   34    0  824    6    3   16    1]
 [   9    3    0    1    8    6  927    0    4    0]
 [   4    9   24    5    4    2    0  966    6    8]
 [   3    3    2   13    7    7    5    4  927    3]
 [   4    8    1   13   29    2    1    7   11  933]]
             precision    recall  f1-score   support

          0       0.96      0.99      0.98       980
          1       0.98      0.99      0.98      1135
          2       0.96      0.95      0.96      1032
          3       0.93      0.97      0.95      1010
          4       0.95      0.96      0.95       982
          5       0.97      0.92      0.95       892
          6       0.96      0.97      0.96       958
          7       0.97      0.94      0.96  